services:
  trackrecord:
    build: .
    container_name: trackrecord-app
    ports:
      - "8081:8000"
    volumes:
      - ./data:/app/data
      - ./run_page/settings.yaml:/app/run_page/settings.yaml
      - ./run_page/static/photos:/app/run_page/static/photos
    restart: always
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - DB_PATH=/app/data/data.db
      - SYNC_ON_STARTUP=true
